import Head from 'next/head'
import {Container, Row, Col} from "react-bootstrap";

interface Props {
    children?: React.ReactNode;
}

const Layout: React.FC<Props> = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row className="justify-content-center">
            <Col xs={6} md={4}>
                {children}
            </Col>
        </Row>
    </Container>
    </>
  )
}
export default Layout